### ISSUE TITLE
distribution through brew / swift package manager / cocoapods

### ISSUE THREAD

**Issue by djds23** [kayak/SwiftGenStrings#2]
Currently consumers of this project need to clone and build it locally. If this was distributed through a package manager it would make adding this to projects locally a bit easier.

Thanks for open sourcing this project.

**Comment by juraj-blahunka** [comment]
@djds23 Thank you for opening the ticket and bringing our attention to the matter. A distributed binary without having to compile the project would indeed make lives easier for people trying to use this project. Stay tuned :)

**Comment by Johennes** [comment]
We might sadly not be popular enough to make it into the official homebrew repository:

> The software in question must:
> 
> - be maintained (e.g. upstream is still making new releases)
> - be known
> - be stable (e.g. not declared "unstable" or "beta" by upstream)
> - be used
> - have a homepage
> 
> We will reject formulae that seem too obscure, partly because they won’t get maintained and partly because we have to draw the line somewhere.
> 
> We frown on authors submitting their own work unless it is very popular.

**Comment by djds23** [comment]
Maybe cocoapods is an acceptable solution then? `SwiftLint` is distributed through this channel.

Regardless thanks for looking into it @Johennes & @juraj-blahunka! This tool has been very helpful.

**Comment by Johennes** [comment]
@djds23 we released a podspec file for SwiftGenStrings (https://cocoapods.org/pods/SwiftGenStrings). The file was linted successfully and theoretically you should be able to do

```
pod 'SwiftGenStrings'
```

now. However, I was not able to get this working in an actual project, most likely due to my limited knowledge of CocoaPods. Would you mind trying this out and reporting back here?

Also note that we started to distribute binaries on GitHub (see https://github.com/kayak/SwiftGenStrings/releases/latest).

**Comment by djds23** [comment]
I was able to get this to download with cocoa pods by specifying this GitHub repo 

```
  pod 'SwiftGenStrings', git: "git@github.com:kayak/SwiftGenStrings.git"
```

However I was unable to use this pod in an iOS app because the podspec specifies that this is a macOS only dependency. I think that can be changed because although this project won't be run on iOS apps, it can still be a build dependency for iOS apps. 

I changed that in my own fork here:

https://github.com/djds23/SwiftGenStrings/commit/91b95d54c61264b9d96d454609373468b997022e

Even after this, I was still not seeing cocoapods actually build the dependency on my local machine and was not able to locate the final binary. Will keep looking into this later this week.

Also thanks a ton for adding the prebuilt binaries to the releases tab. that is another good idea for distribution.

**Comment by Johennes** [comment]
Ok, I figured this out. I had to set up the podspec to download the prebuilt binary instead of compiling the project. In addition, the binary had to be wrapped in a ZIP. I landed this on master and updated the released spec. CocoaPods instructions in the `README` are also complete now.

**Comment by djds23** [comment]
Thanks for taking the time to do this @Johennes
