### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by tempire** [kayak/SwiftGenStrings#4]
`find . -name "*.swift" | xargs SwiftGenStrings`

Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=260 "The file “Supporting” couldn’t be opened because there is no such file." UserInfo={NSFilePath=./Pods/Log/Source/Supporting, NSUnderlyingError=0x7fd7c5007b80 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}: file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-902.0.48/src/swift/stdlib/public/core/ErrorType.swift, line 184

**Comment by juraj-blahunka** [comment]
@tempire You might want to modify the find command to exclude any external dependencies, like Pods or Carthage.
Please try (or modify according to your project structure or neeeds):
```
find . \( -name "*.swift" ! -path "./Carthage/*" ! -path "./Pods/*" \) | xargs SwiftGenStrings
```
