### ISSUE TITLE
SwiftGenStrings not found

### ISSUE THREAD

**Issue by Gargo** [kayak/SwiftGenStrings#7]
installed via mint

**Comment by henrik-dmg** [comment]
Could you please provide some more context? Have you made sure to link the executable correctly? See https://github.com/yonaskolb/Mint#linking for more info

**Comment by Gargo** [comment]
@henrik-dmg `SwiftGenStrings` by itself doesn't work it works when I use `mint run SwiftGenStrings` only. So how to make `SwiftGenStrings` working separately or how to add `mint run` in examples from readme?

**Comment by henrik-dmg** [comment]
Please refer to the `Linking` section of the Mint documentation that I linked above. You need to add `~/.mint/bin` to your `$PATH`. Then you will be able to run `SwiftGenStrings` without having to add `mint run`

Closing this issue as it is not SwiftGenStrings related
